version: "3.9"
services:
  app:
    #image: todoapp:v1
    build: .
    ports:
      - "3000:3000"
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DB: todos

    volumes:
      # - data-volume:/etc/todos/
      - ./src:/app/src/
    depends_on:
      - db  

  db:
   image: mysql
   command: --default-authentication-plugin=mysql_native_password
   restart: always
   environment: 
     MYSQL_ROOT_PASSWORD: password
     MYSQL_DATABASE: todos
   volumes:
     - data-db:/var/lib/mysql

volumes:
   data-volume:
   data-db: 

