name: Docker Compose Todo-App

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Descarga del Repositorio
        uses: actions/checkout@v2
        
      - name: Empezar Containers
        run: docker compose -f "docker-compose.yml" up -d --build
