name: Docker Compose Todo-App

on:
  push:
    branches: [ "main" ]



jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Descarga del Repositorio
        uses: actions/checkout@v2
      
      - name: Montar Docker Compose
        uses: docker/compose-cli@v1
        with:
          compose-file: ./app/docker-compose.yaml
          compose-command: up

