name: Docker Compose Todo-App

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: [self-hosted, build]
    steps:
      - name: Descarga del Repositorio
        uses: actions/checkout@v2
        
      - name: Construir Containers
        working-directory: ./app
        #run: docker compose -f "docker-compose.yaml" up -d --build
        run: docker compose -f "docker-compose.yaml" build 
        
      - name: Configurar DockerHub
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASS: ${{secrets.DOCKER_PASS}}
        run: docker login -u $DOCKER_USER -p $DOCKER_PASS
        
      - name: Subir Compose
        working-directory: ./app
        run: |
          docker compose push
  deploy:
    needs: build
    runs-on: [self-hosted, deploy]
    steps:
      - name: Descarga del Repositorio
        uses: actions/checkout@v2

      - name: Iniciar DockerCompose
        working-directory: ./app
        run: docker compose -f "docker-compose.yaml" up -d
